[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
feature_words = true                # enable completion by word
feature_snippets = true              # enable snippets
snippets_first = true                # completions will return before snippets by default
snippets_inline_by_word_tail = true # suggest snippets by WORD tail, for example text `xsq|` become `x^2|` when snippet `sq` has body `^2`
feature_unicode_input = false        # enable "unicode input"
feature_paths = false                # enable path completion
feature_citations = false            # enable citation completion (only on `citation` feature enabled)


[language-server.nimlsp]
command = "nimlsp"
config.documentFormatting = true
config.hostInfo = "helix"

[[language]]
name = "nim"
auto-format = true
language-servers = [
  {name = "nimlsp"},
]

[[language]]
name = "cpp"
auto-format = true

[[language]]
name = "c"
auto-format = true

[[language]]
name = "python"
auto-format = true


[[language]]
name = "rust"
language-servers = [ "scls", "rust-analyzer" ]

[[language]]
name = "css"
auto-format = true

[[language]]
name = "markdown"
auto-format = true

[language-server.rust-analyzer]
rust-analyzer.cachePriming.enable = false


[[language]]
name = "nix"
scope = "source.nix"
auto-format = true
language-servers = ["nixd"]

[language-server.nixd]
command = "nixd"
config.documentFormatting = true
config.hostInfo = "helix"

[[language]]
name = "lean"
language-servers = [ "scls", "lean" ]

